# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'UILabelHeight' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'UILabelHeight', '~>0.0.2'
  # Pods for UILabelHeight


  target 'UILabelHeightTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UILabelHeightUITests' do
    # Pods for testing
  end

end
